version: '3.1'

services:
  nginx:
    image: nginx
    container_name: flatype_nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - web
    volumes:
      - "./static:/usr/projects/flatype/static"
      - "./nginx:/etc/nginx/conf.d"

  web:
    build: .
    container_name: flatype_web
    image: flatype_image
    command: bash -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 flatype.wsgi --reload"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ".:/usr/projects/flatype"
