# Generated by Django 3.2.4 on 2021-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_article_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='owner_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
