# Generated by Django 3.2.2 on 2021-05-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='data',
            new_name='date',
        ),
    ]
