# Generated by Django 3.2.4 on 2021-08-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_article_owner_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner_hash',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
