# Generated by Django 3.2.4 on 2021-08-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210807_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_data', models.TextField()),
                ('storage_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
