# Generated by Django 3.2.4 on 2021-08-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage object', 'verbose_name_plural': 'Storage'},
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='storage_data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='storage_file',
            new_name='file',
        ),
    ]
