# Generated by Django 3.2.4 on 2021-08-15 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
