# Generated by Django 3.2.4 on 2021-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_storage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='file',
            field=models.FileField(db_index=True, unique=True, upload_to=''),
        ),
    ]
