# Generated by Django 3.2.6 on 2021-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_storage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
    ]
