# Generated by Django 3.2.6 on 2021-08-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_storage_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, unique=True),
        ),
    ]
