# Generated by Django 3.2.6 on 2021-08-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='use_hash',
            field=models.BooleanField(default=True),
        ),
    ]
