# Generated by Django 3.2.6 on 2021-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_storage_use_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
