# Generated by Django 3.2.7 on 2021-09-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_storage_hash'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='storage',
            table='storage',
        ),
    ]
