# Generated by Django 3.2.7 on 2021-09-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('core', '0023_auto_20210912_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner_hash',
        ),
        migrations.AddField(
            model_name='article',
            name='owner_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
