# Generated by Django 3.2.7 on 2021-09-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('core', '0025_rename_text_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner_session',
        ),
        migrations.AddField(
            model_name='article',
            name='owner_session',
            field=models.ManyToManyField(to='sessions.Session'),
        ),
    ]
