# Generated by Django 3.2.7 on 2021-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('core', '0027_rename_owner_session_article_owner_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner_sessions',
            field=models.ManyToManyField(blank=True, to='sessions.Session'),
        ),
    ]
