# Generated by Django 3.2.7 on 2021-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('core', '0028_alter_article_owner_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner_sessions',
            field=models.ManyToManyField(blank=True, db_table='article_owners', to='sessions.Session'),
        ),
    ]
