# Generated by Django 3.2.7 on 2021-09-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ext_auth', '0002_auto_20210912_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalSession',
        ),
    ]
