# Generated by Django 3.2.7 on 2021-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_auth', '0003_delete_externalsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, help_text='150 characters or fewer. Link to account on the site.', null=True, verbose_name='user link'),
        ),
    ]
