# Generated by Django 3.2.7 on 2021-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ext_auth', '0004_auto_20210914_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, db_table='auth_user_permissions', help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user_permissions'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
